services:
  reverse-proxy:
    image: traefik:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - "traefik.http.middlewares.to-ssl-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.to-ssl-redirectscheme.redirectscheme.permanent=true"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.secureweb.address=:443
      - --certificatesresolvers.le.acme.email=volatileasm@protonmail.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --entryPoints.web.forwardedHeaders.insecure
      - --log
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates

  webserver:
    image: nginx:latest
#    build: .
#    volumes:
#      - ./public:/var/www/html
#      - ./nginx/templates:/etc/nginx/templates
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/nginxconfig/general.conf:/etc/nginx/general.conf
#      - ./nginx/nginxconfig/security.conf:/etc/nginx/security.conf
#      - ./build:/usr/share/nginx/html
    restart: always
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.webserver-http.entrypoints=http
      - traefik.http.routers.webserver-http.rule=Host(`localhost`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.webserver-https.entrypoints=https
      - traefik.http.routers.webserver-https.rule=Host(`localhost`)
      - traefik.http.routers.webserver-https.tls=true
      - traefik.http.routers.webserver-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.webserver.loadbalancer.server.port=80
      - traefik.http.routers.webserver-http.middlewares=https-redirect
    links:
      - php-fpm
      - outline_admin

  php-fpm:
    image: php:8-fpm
    networks:
      - traefik-public

  outline_admin:
    image: slaweekq/outline_admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-9696}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
#    volumes:
#      - ".:/var/www/html"
    environment:
      - PORT=9696
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.outline_admin-http.entrypoints=http
      - traefik.http.routers.outline_admin-http.rule=Host(`localhost`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.outline_admin-https.entrypoints=https
      - traefik.http.routers.outline_admin-https.rule=Host(`localhost`)
      - traefik.http.routers.outline_admin-https.tls=true
      - traefik.http.routers.outline_admin-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.services.outline_admin.loadbalancer.server.port=80
      - traefik.http.routers.outline_admin-http.middlewares=https-redirect
    restart: unless-stopped

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    driver: bridge
    external: true
